---
# tasks file for ansible-role-echo

- name: echo FQDN
  command: hostname -f
  register: out

- name: echo FQDN
  debug: var=out.stdout

- name: echo IP address
  command: hostname -I
  register: out

- name: echo IP address
  debug: var=out.stdout

- name: echo python version
  script: echo.py
  register: out

- name: echo python version
  debug: var=out.stdout

